# Generated by Django 4.1.7 on 2023-04-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_email_send_email_email1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Send_email',
        ),
        migrations.DeleteModel(
            name='Send_feedback',
        ),
    ]
