# Generated by Django 4.1.7 on 2023-04-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_send_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=254)),
            ],
        ),
    ]
