# Generated by Django 4.1.7 on 2023-04-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_send_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_email',
            name='feedback',
            field=models.CharField(default=' ', max_length=254),
            preserve_default=False,
        ),
    ]
